<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Machine" Id="{66cd1380-c52f-4694-bc09-18455997d862}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Machine EXTENDS FB_PackML_BaseModule
VAR
	Boiler		: 	I_Boiler;
	Dispenser	: 	I_Dispenser;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="CyclicLogic" Id="{041eac44-05ea-481d-bf59-fdcc1dd5374b}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD CyclicLogic
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>