<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Boiler" Id="{34b3672c-408e-44c2-8295-16ea1aa1e18a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Boiler EXTENDS FB_PackML_BaseModule IMPLEMENTS I_Boiler
VAR
	// Interfaces
	HeatingElement 	:	I_HeatingElement;
	TempSensor 		: 	I_TempSensor;
	
	// FBs
	ImmersionHeater	: FB_ImmersionHeater;
	RtdSensor		: FB_RtdSensor;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="ChangeMode" Id="{43448d4d-2522-40a1-b71d-e0027a42f791}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD ChangeMode
VAR_INPUT
	Mode	: SPT_BaseTypes.E_PMLUnitMode;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="ChangeState" Id="{c2f27d80-047c-4c0d-a46a-7f96c8ba00ca}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD ChangeState
VAR_INPUT
	State	: SPT_BaseTypes.E_PMLCommand;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="CurrentMode" Id="{12b4bdf5-2bd2-44ff-8e69-acd9a364bec8}">
      <Declaration><![CDATA[{error 'Add property implementation or delete property to use base implementation'}
PROPERTY CurrentMode : SPT_BaseTypes.E_PMLUnitMode
]]></Declaration>
      <Get Name="Get" Id="{a3313aba-bf57-4182-9b2e-2f32aeb3af71}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="CurrentState" Id="{5bde3a48-65c8-4f8e-9bde-c9a29d4aa4ef}">
      <Declaration><![CDATA[{error 'Add property implementation or delete property to use base implementation'}
PROPERTY CurrentState : SPT_BaseTypes.E_PMLState
]]></Declaration>
      <Get Name="Get" Id="{a529a9de-a819-4ce5-b384-24a15b580026}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="CyclicLogic" Id="{5091d7f9-b204-46ec-936d-18b529bb496d}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD CyclicLogic
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Disable" Id="{f60e66fc-af66-444e-adf7-cb5c9addbc75}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD Disable : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Enable" Id="{cdb83fee-485f-4db6-b4ca-82ec4e83e942}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD Enable : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="SetpointMet" Id="{ab534255-e398-44fe-ac3f-14ee4188a5b0}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY SetpointMet : BOOL
]]></Declaration>
      <Get Name="Get" Id="{cb0dd34b-d7a4-4a3b-b956-35c089498b32}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="TemperatureSetpoint" Id="{9c79338d-b453-42c1-a2fe-92ffdeaf30a0}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY TemperatureSetpoint : LREAL
]]></Declaration>
      <Get Name="Get" Id="{fad31b38-fa26-4abb-83ae-0df8a9d07515}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{3fff3071-2f7a-43de-9b8c-508fbc602e15}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
  </POU>
</TcPlcObject>